### ISSUE TITLE
#.,00,, and #.0,##0,, don't work

### ISSUE THREAD

**Issue by MartinDawson** [borgar/numfmt#11]
Hi @borgar 

thanks for the library, it's really good.

I tried the above two formats and they don't work. Same bug in the original SSF library.

So, this format works instead: #,##0.00,,.

The issue seems to arise from having a decimal before a comma. I think the fix for this might be to switch .0 to the end of the string.

Failing test:

```js
test("Exponential: #.0,##0,,", (t) => {
  const _f = fmt("#.0,##0,,");
  t.is(_f(45340000000), "45,340.00");
  t.end();
});
```

Passing test:

```js
test("Exponential: #,##0.0,,", (t) => {
  const _f = fmt("#,##0,,");
  t.is(_f(45340000000), "45,340");
  t.end();
});
```

The bug seems to be in parsePart.js:

```js
else if (
      (current_pattern === 'int' && (m = /^[#?0]+(?:,[#?0]+)*/.exec(s))) ||
      (current_pattern === 'den' && (m = /^[#?\d]+/.exec(s))) ||
      (m = /^[#?0]+/.exec(s))
    ) {
      part[current_pattern + '_pattern'].push(m[0]);
      last_number_chunk = { type: current_pattern, num: m[0] };
      add(last_number_chunk, tokens);
    }
```

For the failing test it only parses the first char: `#` when it should be doing: `#,##0`. I.e it needs to ignore any decimal that comes before the comma I think.

Not sure if this is the only place to do the fix but if I get some free time later I can try and do the fix if it's still outstanding.

**Comment by borgar** [comment]
The format string is nonsense, so I did some quick testing:

* This doesn't work in Excel either. It simply refuses to allow you to enter the format string "normalizing" it to `#.0##0,,`. It would be interesting to manually construct an xslx with this inside to see what happens. 🤔 

* Google Sheets does indeed emit `45,340.00` for 45340000000. They interpret the format to be equivalent to `#,###.00##,,` 

I am curious to the origin of the string. Why do you expect this to work?

**Comment by MartinDawson** [comment]
Ah I see. I guess GSheets is just correcting an incorrect format then from me.

I was just trying to format numbers with commas and decimals in the millions format. Because it worked in GSheets I presumed there was an issue with the library.

Thanks for clarifying. I think this can be closed then if Excel doesn't allow it.
