### ISSUE TITLE
Custom format `#.###0` not working

### ISSUE THREAD

**Issue by dantronik-markus** [borgar/numfmt#18]
According to https://customformats.com/, when I enter `#.###0` as custom format, for example:
-10.29 should be formatted as -10.290

However:
```js
numfmt.format("#.###0", -10.29)
'-10.29'
```

**Comment by dantronik-markus** [comment]
My local Excel version displays the number as -10.290 as well. (or rather -10,290 in the German version).

**Comment by borgar** [comment]
Yep. This is clearly an error. Will take a look asap.
