### ISSUE TITLE
Specific format string not working correctly for negative numbers

### ISSUE THREAD

**Issue by dantronik-markus** [borgar/numfmt#27]
We have the following number format string in the German version of Excel:
`[>=100]#.##0;[<=-100]-#.##0;#.##0,00`

If we format the number -3,96 with it, the number gets output properly as -3,96.

In order to use the number format string with numfmt, we swap the "," and "." characters (because thousands separator and decimal separator are swapped in German), like so:

```js
"[>=100]#.##0;[<=-100]-#.##0;#.##0,00"
.replaceAll(",", "|")
.replaceAll(".", ",")
.replaceAll("|", ".")
.replaceAll("Rot", "Red")
.replaceAll("ROT", "RED")
.replaceAll("rot", "red")
.replaceAll("JJJJ", "yyyy");
```

Which gives me `'[>=100]#,##0;[<=-100]-#,##0;#,##0.00'`

Interestingly enough, the negative number -3.96 gets formatted as 3.96 (even on https://customformats.com/).

I am not sure if this is an issue with the way we parse / replace custom number formats (whether the format string is supposed to be different in the English version of Excel) or whether there's something else going on.

Could you test the English format string with the English version of Excel if you have it?

**Comment by borgar** [comment]
I've tested this on my local Excel (and Google Sheets) which have english defaults and can confirm this is a bug. 

`-3.96` formatted with `[>=100]#,##0;[<=-100]-#,##0;#,##0.00` should result in `"-3.96"`

I have not done much testing but my working hypothesis is that the third "else" part of the equation (the one without a condition) gets an "optional minus" added when conditions are present in the pattern. This woulds be similar to how `#,###` gets turned into `#,###;-#,###;0;@` behind the scenes. 

I'll try to patch this asap.

**Comment by borgar** [comment]
I've just published an update with a fix for this.
