### ISSUE TITLE
Consider supporting conditionals

### ISSUE THREAD

**Issue by sarimarton** [borgar/numfmt#37]
It's not support of ECMA 376, but Excel, Google Sheets and ssf all support them and it seems to be a relatively easy feat. It's very useful for the typical k-m-b formatting:

E.g.: `[>=950000000]0.#,,"B";[>=950000]0.#,,"M";[>=950]0.#,"k";0.##`

**Comment by sarimarton** [comment]
Can you give more info on this?

The README doesn't mention the conditionals, the linked Microsoft website barely say anything about the conditionals, giving 1 pretty simple example

> Specify conditions
> To specify number formats that will be applied only if a number meets a condition that you specify, enclose the condition in square brackets. The condition consists of a comparison operator and a value. For example, the following format displays numbers that are less than or equal to 100 in a red font and numbers that are greater than 100 in a blue font.> [Red][<=100];[Blue][>100]

My example is valid in google sheets and ssf, but not in Excel, which, again, doesn't give any hint what's wrong with the format.

**Comment by borgar** [comment]
I don't know how you get Google Sheets to accept this but they are refusing it for me:

<img width="522" alt="Screen Shot 2023-02-27 at 14 54 24" src="https://user-images.githubusercontent.com/21862/221600949-3de932ae-bcf4-47aa-b6c2-cae9c8c5d785.png">

So if SSF accepts this then I'd call that a bug. 🤷 

I've added some minimal text about conditionals to the README, including the rules that govern the pattern sections.

Basically your pattern is violating two rules:

- There is a maximum of 2 conditions.
- There text section must not contain numerical or date operators.

Conditions effectively makes the pattern work like this:

1. Condition 1
2. Condition 2
3. Else number (used when input is number)
4. Else text (used when input is non-number such as text or bool)

So you can really only add conditions for section 1 and 2. The third must be a "else case" for numbers, and the fourth is an else case for when input is not a number.

**Comment by sarimarton** [comment]
Indeed, the format I'm using for google sheets is without the B:

`[>=950000]0.0,,\M;[>=950]0.0,\k;0`

This is accepted by all 4 players (google, excel, ssf, numfmt). Thanks for the explanation, I've found [google's rules](https://developers.google.com/sheets/api/guides/formats#meta_instructions) as well in the meantime.

It's a bummer that the format cannot be used to render a k-m-b representation (only k and m).
