### ISSUE TITLE
0.00_ parse error

### ISSUE THREAD

**Issue by sunnyawake5** [borgar/numfmt#54]
0.00_ parse error:
SyntaxError: Illegal character: 0.00_ (at parseFormatSection.js:436:13)
    at parseFormatSection (parseFormatSection.js:436:13)
    at parsePattern (parsePattern.js:48:12)
    at prepareFormatterData (index.js:45:19)

**Comment by borgar** [comment]
That seems to be correct behavior. `0.00_` is not a legal format pattern and should throw an error.

If you want the formatter to handle invalid patterns for you, you need to enable that via an option:

```js
format("0.00_", 12.34, { throws: false }); // → "######"
```

Also, consider - if you think this pattern comes from a trusted source, that you may have an error in you application that it is trimming the pattern strings where it should not: `0.00_ ` is a valid pattern.
