### ISSUE TITLE
Add LICENSE.md

### ISSUE THREAD

**Issue by ben-lewis-wtw** [borgar/numfmt#58]
The `package.json` states that the package is published under the MIT license, but there's no further information on licensing beyond this. For avoidance of doubt, please could we add a `LICENSE.md` file to the repository? There's a helpful guide [here](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository) that shows how to apply a license template.

**Comment by borgar** [comment]
Thanks for reporting. I don't know how I managed to forget to add a license file.

License is in the repo and the latest package: @3.1.4
